import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Appbar from '@/components/Appbar'
import Button from '@/components/Button'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appbar>
          <Appbar.Item href="/" active>
            Home
          </Appbar.Item>
          <Appbar.Item href="/about">
            About
          </Appbar.Item>
          <Appbar.Item href="/events">
            Events
          </Appbar.Item>
        </Appbar>
        {children}
        <Footer />
      </body>
    </html>
  )
}
